version: '3'
services:
  apache:
    image: php:7.0-apache
    hostname: apache
    ports:
    - "80:80" # normal php port for trafic and functionality
    volumes:
      - ./app:/var/www/html
  
  mysql:
    image: mysql:8.0
    hostname: mysql
    ports:
      - "3306:3306" # mysql connection port
    environment:
      MYSQL_USER_FILE: var/lib/mysql-user
      MYSQL_PASSWORD_FILE: var/lib/mysql-user-p
      MYSQL_DATABASE_FILE: var/lib/mysql-db
      MYSQL_ROOT_PASSWORD_FILE: var/lib/mysql-root-p
    volumes:
      - ./data:/var/lib/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - mysql
    ports:
      - "8183:80" # phpmyadmin login page
    environment:
      PMA_USER: root22
      PMA_PASSWORD: root22
      PMA_ARBITRARY: 1